stages:
  - lint
  - build
  - test
  - release
  - publish

lint:
  image: registry.furqansoftware.net/cardboard/golang:1.24.1-bullseye-0
  stage: lint
  script:
    - make lint.tools.install
    - make lint
  rules:
    - changes:
        - "**/*.go"
        - .gitlab-ci.yml
        - Makefile
    - if: "$CI_COMMIT_TAG"
  cache:
    key: go
    paths:
      - ".go-build"
  interruptible: true

build:
  image: registry.furqansoftware.net/cardboard/golang:1.24.1-bullseye-0
  stage: build
  script:
    - go build -o printd .
  rules:
    - changes:
        - "**/*.go"
        - .gitlab-ci.yml
        - Makefile
    - if: "$CI_COMMIT_TAG"
  artifacts:
    expire_in: 3 hours
    paths:
      - printd
  cache:
    key: go
    paths:
      - ".go-build"
  interruptible: true

test:
  image: registry.furqansoftware.net/cardboard/golang:1.24.1-bullseye-0
  stage: test
  script:
    - make test
  rules:
    - changes:
        - "**/*.go"
        - .gitlab-ci.yml
        - Makefile
    - if: "$CI_COMMIT_TAG"
  needs:
    - build
  cache:
    key: go
    paths:
      - ".go-build"
    policy: pull
  interruptible: true

release:
  stage: release
  image:
    name: goreleaser/goreleaser:v2.8.1
    entrypoint: [""]
  variables:
    GIT_DEPTH: 0
  script:
    - make goversioninfo.install
    - goreleaser release --clean --skip=publish `if [[ "$CI_COMMIT_TAG" == "" ]]; then echo --snapshot; fi`
  artifacts:
    expire_in: 3 hours
    paths:
      - dist/

publish:
  stage: publish
  image:
    name: goreleaser/goreleaser:v2.8.1
    entrypoint: [""]
  only:
    - tags
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser publish
  needs:
    - release
