stages:
  - lint
  - build
  - test
  - release

lint:
  image: cardboard/golang:1.19.4
  stage: lint
  script:
  - make lint.tools.install
  - make lint
  rules:
  - changes:
    - "**/*.go"
  - if: "$CI_COMMIT_TAG"
  cache:
    key: go
    paths:
    - ".go-build"
  interruptible: true

build:
  image: cardboard/golang:1.19.4
  stage: build
  script:
  - go build -o printd .
  rules:
  - changes:
    - "**/*.go"
  - if: "$CI_COMMIT_TAG"
  artifacts:
    expire_in: 3 hours
    paths:
    - printd
  cache:
    key: go
    paths:
    - ".go-build"
  interruptible: true

test:
  image: cardboard/golang:1.19.4
  stage: test
  script:
  - make test
  rules:
  - changes:
    - "**/*.go"
  - if: "$CI_COMMIT_TAG"
  needs:
  - build
  cache:
    key: go
    paths:
    - ".go-build"
    policy: pull
  interruptible: true

release:
  stage: release
  image:
    name: goreleaser/goreleaser:v1.14.1
    entrypoint: ['']
  only:
    - tags
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser release --rm-dist
