project_name: printd
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.txt
      - README.md
      - UBUNTU_FONT_LICENCE.txt
release:
  github:
    owner: FurqanSoftware
    name: toph-printd
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
